//Global
export const ERROR = 'ERROR';
export const LOADING = 'LOADING';

//Category
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const REMOVE_CATEGROY = 'REMOVE_CATEGROY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const GET_ACTIVITIES_UNDER_CATEGORY = 'GET_ACTIVITIES_UNDER_CATEGORY';

//Learning Activity
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';

